# por defecto este archivo es dev.yml

version: '2'

services:
  # contenedor db con pgsql, extiende de base.yml
  db:
    extends:
      file: base.yml
      service: db

  # contenedor para django, extiende de base.yml
  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        # instala requirements/dev.txt
        - DJANGO_ENV=dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dj_docker:/dj_docker
    ports:
      - "8000:8000"
    depends_on:
      - db

# volumenes persistentes
volumes:
  db_data:
    external: true